language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST=""
    - PREFER_LOWEST="--prefer-lowest"

php:
  - 7
  - 5.6
  - 5.5
  - hhvm

before_install:
  - composer self-up
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  - composer update --no-interaction --prefer-stable $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  - ./vendor/bin/behat -f progress

matrix:
  fast_finish: true
