language: php

sudo: false

cache:
  directories:
    - $HOME/.config/composer/cache

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - composer self-up
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  - if [[ $PREFER_LOWEST -ne "" || ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer up --ignore-platform-reqs && composer remove --ignore-platform-req --dev zendframework/zend-mvc-i18n; fi
  - composer update --no-interaction --prefer-stable $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  - ./vendor/bin/behat -f progress

matrix:
  fast_finish: true
