<?php

/**
 * Copyright 2016 Fabian Grutschus. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the copyright holders.
 *
 * @author    Fabian Grutschus <f.grutschus@lubyte.de>
 * @copyright 2016 Fabian Grutschus. All rights reserved.
 * @license   BSD-2-Clause
 * @link      https://github.com/fabiang/zf-localize-helper
 */

namespace Fabiang\LocalizeHelper;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\ServiceManager\ServiceLocatorInterface;
use Zend\ServiceManager\ServiceManager;
use Zend\I18n\Validator\DateTime as Validator;
use Zend\I18n\Filter\Alnum as Filter;
use Zend\I18n\View\Helper\DateFormat as ViewHelper;
use Zend\Mvc\I18n\Translator as MvcTranslator;
use Zend\I18n\Translator\Translator as Translator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-28 at 13:09:06.
 *
 * @coversDefaultClass Fabiang\LocalizeHelper\LocaleInitializer
 */
final class LocaleInitializerTest extends TestCase
{
    /**
     * @var LocaleInitializer
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LocaleInitializer();
    }

    /**
     * @test
     * @covers ::__invoke
     * @covers ::getLocale
     */
    public function testInvoke()
    {
        $validator  = $this->prophesize(Validator::class);
        $validator->setLocale('en_US')->shouldBeCalled();
        $filter     = $this->prophesize(Filter::class);
        $filter->setLocale('en_US')->shouldBeCalled();
        $viewHelper = $this->prophesize(ViewHelper::class);
        $viewHelper->setLocale('en_US')->shouldBeCalled();

        $translator = $this->prophesize(Translator::class);
        $translator->getLocale()->willReturn('en_US');

        $mvcTranslator = $this->prophesize(MvcTranslator::class);
        $mvcTranslator->getTranslator()->willReturn($translator->reveal());

        $container = $this->prophesize(ServiceLocatorInterface::class);
        $container->has('MvcTranslator')->willReturn(true);
        $container->get('MvcTranslator')->willReturn($mvcTranslator->reveal());

        $this->object->__invoke($container->reveal(), $validator->reveal());
        $this->object->__invoke($container->reveal(), $filter->reveal());
        $this->object->__invoke($container->reveal(), $viewHelper->reveal());
    }

    /**
     * @covers ::getLocale
     */
    public function testInvokeNoMvcTranslator()
    {
        $container = $this->prophesize(ServiceLocatorInterface::class);
        $container->has('MvcTranslator')->willReturn(false);

        $validator  = $this->prophesize(Validator::class);
        $validator->setLocale()->shouldNotBeCalled();

        $this->object->__invoke($container->reveal(), $validator->reveal());
    }

    /**
     * @covers ::initialize
     */
    public function testInitialize()
    {
        $sm = new ServiceManager();
        if (!method_exists($sm, 'getServiceLocator')) {
            $this->markTestSkipped();
        }

        $validator  = $this->prophesize(Validator::class);
        $validator->setLocale('en_US')->shouldBeCalled();

        $translator = $this->prophesize(Translator::class);
        $translator->getLocale()->willReturn('en_US');

        $mvcTranslator = $this->prophesize(MvcTranslator::class);
        $mvcTranslator->getTranslator()->willReturn($translator->reveal());

        $container = $this->prophesize(ServiceLocatorInterface::class);
        $container->has('MvcTranslator')->willReturn(true);
        $container->get('MvcTranslator')->willReturn($mvcTranslator->reveal());

        $globalContainer = $this->prophesize(ServiceManager::class);
        $globalContainer->getServiceLocator()->willReturn($container);
        
        $this->object->initialize(
            $validator->reveal(),
            $globalContainer->reveal()
        );
    }
}
